services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-race-authkey-container
    hostname: race-engineer-dashboard-tailscale-service
    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID:-}
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET:-}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTH_ONCE=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:ros-device --ssh=true
      - TS_ENABLE_HEALTH_CHECK=true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9002/healthz"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    volumes:
      - ts-authkey-container:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure:3
    environment:
      - ROS_DOMAIN_ID=14
      - ROS_LOCALHOST_ONLY=0
      - DISCOVERY_SERVER_IP=100.110.98.26
    depends_on:
      tailscale:
        condition: service_healthy
    network_mode: service:tailscale

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY:-}
        - VITE_GOOGLE_MAP_ID=${VITE_GOOGLE_MAP_ID:-}
      dockerfile: Dockerfile
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY:-}
      - VITE_GOOGLE_MAP_ID=${VITE_GOOGLE_MAP_ID:-}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  ts-authkey-container:
    driver: local

networks:
  app-network:
    driver: bridge
