services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-race-authkey-container
    hostname: race-engineer-dashboard-tailscale-service
    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID:-}
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET:-}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTH_ONCE=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:ros-device --ssh=true
      - TAILSCALE_TAG_NAME=tag:ros-device
    volumes:
      - ts-authkey-container:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - .:/workspace
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD", "test", "-f", "/workspace/fast.xml"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - app-network

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=telemetry_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - postgres
      - redis
    restart: on-failure:3
    networks:
      - app-network

  subscriber:
    build:
      context: ./backend/subscriber
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=telemetry_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ROS_DOMAIN_ID=14
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      tailscale:
        condition: service_started
    restart: on-failure:3
    network_mode: service:tailscale

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      # use service name, not localhost
      - API_BASE_URL=http://api:8000
    networks:
      - app-network

volumes:
  ts-authkey-container:
    driver: local

networks:
  app-network:
    driver: bridge
